# The Redis server you use.
# Get Redis from http://redis.io/
redis-server: 127.0.0.1
redis-port: 6379

# An identifier for this BungeeCord instance.
server-id: iluvbungee

# Whether or not /glist showall output should match vanilla BungeeCord.
canonical-glist: true

# Output all players in the server list. Recommended only for smaller networks.
player-list-in-ping: false

# All other RedisBungee server IDs in the network.
linked-servers:
- dastank
- americancoffee
- guavaissweet